### ISSUE TITLE
.htaccess file?

### ISSUE THREAD

**Issue by travis1111** [eclipse/che-website#13]
Hi, this Travis, from Codewind project.  This is not a bug report, instead, a question regarding .htaccess file on eclipse.org. I saw you have a _hataccess file in some of your folders which adds .html to urls without .html extension.  We have added .htaccess file to our site, but it is not working.  Just wondering is there any trick to make it it work?  We need to add .html to the urls too :-)

Thanks!

**Comment by slemeur** [comment]
Hi @travis1111 ! 

No I think we had it for historical reason but it never worked.

**Comment by travis1111** [comment]
Thanks!
