### ISSUE TITLE
After running command, preview link does not show website

### ISSUE THREAD

**Issue by dneary** [eclipse/che-website#14]
After running the command, I get a message that an application is listening on port 80, and asking if I would like to redirect so that I can access it. I clicked yes, and after a few seconds, the link showed https://routeflsy1t2z-dneary-che.b542.starter-us-east-2a.openshiftapps.com/ - an Apache index with /che-website and /che in it. I clicked on /che and saw a preview of the website. I was expecting to have the preview link show the website directly. If it's possible to have the preview link include "/che", it would make it easier to get to the preview.

**Comment by benoitf** [comment]
hello @dneary 
issues need to be created on the main che repository (as explained when trying to use new issue button and inside the templates)
